use crate::models::assessment::AuditAssessment;

pub fn render(assessment: &AuditAssessment) -> String {
    let mut out = String::new();

    // Header
    let product = assessment
        .product_name
        .as_deref()
        .unwrap_or("Unknown Product");
    let date = chrono::Utc::now().format("%Y-%m-%d");
    let version = env!("CARGO_PKG_VERSION");

    out.push_str("# CRA Compliance Audit Report\n\n");
    out.push_str(&format!("**Product:** {product}\n"));
    out.push_str(&format!("**Date:** {date}\n"));
    out.push_str(&format!("**Tool:** cra-auditflow v{version}\n\n"));
    out.push_str("---\n\n");

    // CRA Risk Classification
    let cls = &assessment.classification;
    out.push_str("## CRA Risk Classification\n\n");
    out.push_str("| Field | Value |\n");
    out.push_str("|-------|-------|\n");
    out.push_str(&format!("| **Risk Class** | {} |\n", cls.risk_class));

    if let Some(cat) = &cls.matched_category {
        out.push_str(&format!("| **Matched Category** | {cat} |\n"));
    }

    if !cls.matched_keywords.is_empty() {
        out.push_str(&format!(
            "| **Matched Keywords** | {} |\n",
            cls.matched_keywords.join(", ")
        ));
    }

    if !cls.applicable_articles.is_empty() {
        out.push_str(&format!(
            "| **Applicable Articles** | {} |\n",
            cls.applicable_articles.join(", ")
        ));
    }

    out.push_str(&format!(
        "| **Conformity Assessment** | {} |\n",
        cls.conformity_note
    ));
    out.push('\n');

    // Audit Summary
    let s = &assessment.summary;
    out.push_str("## Audit Summary\n\n");
    out.push_str("| Metric | Count |\n");
    out.push_str("|--------|-------|\n");
    out.push_str(&format!("| Total Components | {} |\n", s.total_components));
    out.push_str(&format!(
        "| Components with Vulnerabilities | {} |\n",
        s.components_with_vulns
    ));
    out.push_str(&format!(
        "| Total Vulnerabilities | {} |\n",
        s.total_vulnerabilities
    ));
    out.push_str(&format!("| Critical | {} |\n", s.critical_count));
    out.push_str(&format!("| High | {} |\n", s.high_count));
    out.push_str(&format!("| Medium | {} |\n", s.medium_count));
    out.push_str(&format!("| Low | {} |\n", s.low_count));

    if s.unknown_count > 0 {
        out.push_str(&format!("| Unknown | {} |\n", s.unknown_count));
    }
    out.push('\n');

    // Vulnerability Findings
    if !assessment.findings.is_empty() {
        out.push_str("## Vulnerability Findings\n\n");

        for finding in &assessment.findings {
            if finding.vulnerabilities.is_empty() {
                continue;
            }

            let ver = finding.component_version.as_deref().unwrap_or("unknown");
            out.push_str(&format!("### {} v{}\n\n", finding.component_name, ver));

            if let Some(purl) = &finding.purl {
                out.push_str(&format!("PURL: `{purl}`\n\n"));
            }

            out.push_str("| ID | Severity | Score | Summary |\n");
            out.push_str("|----|----------|-------|---------|\n");

            for vuln in &finding.vulnerabilities {
                let score_str = vuln
                    .max_score()
                    .map(|s| format!("{s:.1}"))
                    .unwrap_or_else(|| "N/A".into());
                let summary = vuln.summary.as_deref().unwrap_or("No description");
                let truncated = if summary.len() > 80 {
                    format!("{}...", &summary[..77])
                } else {
                    summary.to_string()
                };

                out.push_str(&format!(
                    "| {} | {} | {} | {} |\n",
                    vuln.id,
                    vuln.severity_label(),
                    score_str,
                    truncated
                ));
            }
            out.push('\n');
        }
    }

    // SBOM Overview
    out.push_str("## SBOM Overview\n\n");
    out.push_str("| Field | Value |\n");
    out.push_str("|-------|-------|\n");
    out.push_str(&format!("| **Format** | {} |\n", assessment.sbom_format));
    out.push_str(&format!(
        "| **Spec Version** | {} |\n",
        assessment.sbom_spec_version
    ));
    out.push_str(&format!(
        "| **Component Count** | {} |\n",
        assessment.sbom_component_count
    ));
    out.push('\n');

    out.push_str("---\n\n");
    out.push_str(&format!(
        "*Generated by cra-auditflow v{version} on {date}*\n"
    ));

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::assessment::*;

    fn sample_assessment() -> AuditAssessment {
        AuditAssessment {
            product_name: Some("TestProduct".into()),
            classification: CraClassification {
                risk_class: CraRiskClass::ImportantClassI,
                matched_category: Some("Standalone and embedded browsers".into()),
                matched_keywords: vec!["browser".into()],
                applicable_articles: vec!["Article 32".into()],
                conformity_note: "Self-assessment or harmonised standards".into(),
            },
            findings: vec![],
            summary: AuditSummary {
                total_components: 5,
                components_with_vulns: 0,
                total_vulnerabilities: 0,
                critical_count: 0,
                high_count: 0,
                medium_count: 0,
                low_count: 0,
                unknown_count: 0,
            },
            sbom_format: "CycloneDX".into(),
            sbom_spec_version: "1.5".into(),
            sbom_component_count: 5,
        }
    }

    #[test]
    fn renders_markdown_header() {
        let report = render(&sample_assessment());
        assert!(report.contains("# CRA Compliance Audit Report"));
        assert!(report.contains("**Product:** TestProduct"));
    }

    #[test]
    fn renders_risk_classification() {
        let report = render(&sample_assessment());
        assert!(report.contains("Important (Class I)"));
        assert!(report.contains("browser"));
    }

    #[test]
    fn renders_sbom_overview() {
        let report = render(&sample_assessment());
        assert!(report.contains("CycloneDX"));
        assert!(report.contains("1.5"));
    }
}
